-- ==========================================
-- SCRIPT DDL: MIGRACIÓN ODONTONOVA A ORACLE
-- ==========================================

-- 1. Tabla: Pacientes
CREATE TABLE pacientes (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento VARCHAR2(20) NOT NULL,
    numero_documento VARCHAR2(50) NOT NULL UNIQUE,
    nombre VARCHAR2(100) NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Tabla: Odontólogos
CREATE TABLE odontologos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. Tabla: Sillones
CREATE TABLE sillones (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. Tabla: Citas
CREATE TABLE citas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id NUMBER,
    odontologo_id NUMBER NOT NULL,
    sillon_id NUMBER,
    fecha_inicio TIMESTAMP NOT NULL,
    fecha_fin TIMESTAMP NOT NULL,
    motivo CLOB,
    estado VARCHAR2(50) DEFAULT 'PENDIENTE',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_citas_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id) ON DELETE SET NULL,
    CONSTRAINT fk_citas_odontologo FOREIGN KEY (odontologo_id) REFERENCES odontologos(id) ON DELETE CASCADE,
    CONSTRAINT fk_citas_sillon FOREIGN KEY (sillon_id) REFERENCES sillones(id) ON DELETE SET NULL
);

-- 5. Tabla: Tratamientos
CREATE TABLE tratamientos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(150) NOT NULL,
    descripcion CLOB,
    precio NUMBER(10, 2) NOT NULL,
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. Tabla: Cita Tratamiento
CREATE TABLE cita_tratamiento (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id NUMBER NOT NULL,
    tratamiento_id NUMBER NOT NULL,
    cantidad NUMBER DEFAULT 1 NOT NULL,
    precio_unitario NUMBER(10, 2) NOT NULL,
    subtotal NUMBER(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_ct_cita FOREIGN KEY (cita_id) REFERENCES citas(id) ON DELETE CASCADE,
    CONSTRAINT fk_ct_tratamiento FOREIGN KEY (tratamiento_id) REFERENCES tratamientos(id) ON DELETE CASCADE
);

-- 7. Tabla: Historias Clínicas
CREATE TABLE historias_clinicas (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    paciente_id NUMBER NOT NULL,
    odontologo_id NUMBER,
    diagnostico CLOB,
    tratamiento_recomendado CLOB,
    observaciones CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_hc_paciente FOREIGN KEY (paciente_id) REFERENCES pacientes(id) ON DELETE CASCADE,
    CONSTRAINT fk_hc_odontologo FOREIGN KEY (odontologo_id) REFERENCES odontologos(id) ON DELETE SET NULL
);

-- 8. Tabla: Pagos
CREATE TABLE pagos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cita_id NUMBER,
    monto NUMBER(10, 2) NOT NULL,
    metodo_pago VARCHAR2(50) NOT NULL,
    estado VARCHAR2(50) DEFAULT 'COMPLETADO',
    fecha_pago TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_pagos_cita FOREIGN KEY (cita_id) REFERENCES citas(id) ON DELETE SET NULL
);

-- 9. Tabla: Usuarios
CREATE TABLE usuarios (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    email VARCHAR2(150) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    rol VARCHAR2(50) DEFAULT 'RECEPCIONISTA',
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 10. Tabla: Insumos
CREATE TABLE insumos (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100) NOT NULL,
    descripcion CLOB,
    cantidad NUMBER DEFAULT 0 NOT NULL,
    precio_unitario NUMBER(10, 2),
    is_active NUMBER(1) DEFAULT 1 CHECK (is_active IN (0, 1)),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
